### PR TITLE
Include libraries to make jar cross-plattform

### PR DESCRIPTION
**Pull request by anotherHoffmann**

### CODE REVIEW

**Review by YannikPfeiffer — CHANGES_REQUESTED** [review]
would this work?

`<dependency>`
      `<groupId>org.openjfx</groupId>`
      `<artifactId>javafx-graphics</artifactId>`
      `<version>13</version>`
      `<classifier>[linux|mac|...]</classifier>`
`</dependency>`

**Comment by anotherHoffmann** [comment]
> would this work?
> 
> `<dependency>`
> `<groupId>org.openjfx</groupId>`
> `<artifactId>javafx-graphics</artifactId>`
> `<version>13</version>`
> `<classifier>[linux|mac|...]</classifier>`
> `</dependency>`

Sadly no

**Comment by YannikPfeiffer** [comment]
> > would this work?
> > `<dependency>`
> > `<groupId>org.openjfx</groupId>`
> > `<artifactId>javafx-graphics</artifactId>`
> > `<version>13</version>`
> > `<classifier>[linux|mac|...]</classifier>`
> > `</dependency>`
> 
> Sadly no

Darn.

**Review by YannikPfeiffer — APPROVED** [review]
Very gud

**Pull request merged**
